version: '3.5'
# Sample file to use

services:
  tarantool: &tarantool-master
    image: tarantool/tarantool:3
    networks:
      - default
    ports:
      - 3301:3301
      - 6379:6379
      - 11211:11211
    volumes:
      - ./:/opt/tarantool:ro
      - tarantool_data:/var/lib/tarantool:rw
    healthcheck:
      test: ["CMD-SHELL", "status"]
      interval: 1s
    environment: &tarantool-master_env
      TT_APP_NAME: 'keyvalue-emu-app'
      TT_MEMTX_MEMORY: 268435456
      TT_MEMTX_MAX_TUPLE_SIZE: 1048576
      TT_FORCE_RECOVERY: 'true'
      TT_LOG_LEVEL: 'info'
      TT_INSTANCE_NAME: instance-001

  tarantool-replica:
    <<: *tarantool-master
    ports:
      - 3302:3301
      - 6380:6379
    environment:
      <<: *tarantool-master_env
      TT_INSTANCE_NAME: 'instance-002'

volumes:
  tarantool_data:
    external: false
